### ISSUE TITLE
U+11726 AHOM VOWEL SIGN E

### ISSUE THREAD

**Issue by octahedron80** [andjc/ahom-unicode#1]
U+11726 AHOM VOWEL SIGN E must be set to 'front vowel' like Indian scripts; the vowel must be typed after its consonant and it will automatically jump to front. This could be done with some Opentype feature.

**Comment by andjc** [comment]
@octahedron80 ,  this is correct, as yet no OT rules have been added to font, project is in a holding pattern.

The key issue is how to best support Ahom on Windows 10,  Documentation for the Universal Script Engine indicates that Ahom is unsupported, so no explicit shapers are available for Ahom, it may be necessary to use the approach taken by "mymr" style Myanmar fonts. 

TBD
